#!/usr/bin/env python

from helpers import do_curl, get_config
from simplejson import loads as parse_json

webstaq = get_config('webstaq')

def webstaq_cron():
  try:
    data = do_curl(webstaq['cron_url'], key=webstaq['key'])
    print data
    data = parse_json(data.strip())
    print data
  except:
    print 'error'
    pass

def main(args):
  webstaq_cron()

if __name__ == '__main__':
  from sys import argv
  main(argv[1:])